### ISSUE TITLE
Error: Neither WebCryptoAPI nor a crypto module is available.

### ISSUE THREAD

**Issue by nigelpasco** [nigelpasco/lucia-mongoose#1]
App is running without issue in development, however, when creating a production build and previewing I am getting the following error thrown:

```
Error: Neither WebCryptoAPI nor a crypto module is available. Use bcrypt.setRandomFallback to set an alternative
    at random2 (file:///Users/nigelpasco/Documents/GitHub/lucia-mongoose/.svelte-kit/output/server/chunks/lucia.js:84:15)
    at bcrypt2.genSaltSync (file:///Users/nigelpasco/Documents/GitHub/lucia-mongoose/.svelte-kit/output/server/chunks/lucia.js:111:31)
    at Immediate.<anonymous> (file:///Users/nigelpasco/Documents/GitHub/lucia-mongoose/.svelte-kit/output/server/chunks/lucia.js:126:37)
    at process.processImmediate (node:internal/timers:471:21)
```

**Comment by nigelpasco** [comment]
Resolved with lucia v10.1
